### ISSUE TITLE
Implement unit tests

### ISSUE THREAD

**Issue by sbunciak** [testrex-io/testrex-maven-plugin#2]

**Comment by sbunciak** [comment]
@Vojtech-Sassmann provide test case descriptions for review

**Comment by Vojtech-Sassmann** [comment]
* Tests for TestrexConnector:
  * Verify that the `sendReportFile` method send given file to correct url, with correct headers and with correct body.
  * Verify that the `sendReportFile` methods throws Exception if the connection to the server fails.

* Tests for the TestrexMojo:
  * Verify that the mojo sends only correct files and no others.

**Comment by sbunciak** [comment]
Fixed in https://github.com/testrex-io/testrex-maven-plugin/commit/26eaad818be576fc95b97415e5d7aa75a7d99617
